{
 "title": "SampleURL-Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Response Time url 200",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sample_external_url_response_ms{url=\"https://httpstat.us/200\"}"
    }
   ]
  },
  {
   "title": "Response Time url 503",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sample_external_url_response_ms{url=\"https://httpstat.us/503\"}"
    }
   ]
  },
  {
   "title": "Average Response url 200",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sample_external_url_response_ms{url=\"https://httpstat.us/200\"})"
    }
   ]
  },
  {
   "title": "Average Response Time url 503",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sample_external_url_response_ms{url=\"https://httpstat.us/503\"})"
    }
   ]
  },
  {
   "title": "Rate of change of request count over 5 mins",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(sample_external_url_response_latency_ms_count[5m])"
    }
   ]
  }
 ]
}